title: Chelsea Irizarry
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: https://chelseairizarry.github.io/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: ChelseaIrizarry
   twitter: ChelseaIrizarry
   facebook: ChelseaIrizarry
   email: cirizarr@mail.umw.edu

google_analytics: "UA-58263416-1"
