# Site settings
title: Chelsea Irizarry
email: cirizarr@mail.umw.edu
description: > # this means to ignore newlines until "baseurl:"
University of Mary Washington Class of 2017
Computer Science
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://chelseairizarry.github.io/" # the base hostname & protocol for your site
twitter_username: ChelseaIrizarry
github_username:  ChelseaIrizarry

# Build settings
markdown: kramdown
